name: 'Deth Solidity profiler'
description: 'Advance Solidity profiler that is able to generate diffs and produce deterministic results'
author: 'SuperActions'
inputs:
  token:
    default: ${{ github.token }}
  project-path:
    description: 'Absolute path to the hardhat project'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
