name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        node: ['16']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 7.1.0
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - run: pnpm install

      - run: pnpm lint
      - run: pnpm format
      - run: pnpm build

      - run: pnpm test
      - run: pnpm typecheck
      - name: Solidity Profiler
        uses: ./packages/deth-profiler
        with:
          project-path: ./packages/hardhat-example

  run-example:
    needs: test
    strategy:
      matrix:
        node: ['16']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 7.1.0
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - run: pnpm install

      - run: pnpm build

      - uses: ./packages/example

